project_name: trivy-operator-report
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: trivy-operator-report
    ldflags:
      - '-extldflags -static'
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]
    env:
      - CGO_ENABLED=0

archives:
- formats:
    - zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

dockers_v2:
  - id: trivy-operator-report
    ids:
      - trivy-operator-report
    images:
      - ghcr.io/skpr/trivy-operator-report
    tags:
      - "latest"
      - "v{{ .Version }}"
    sbom: false
    flags:
      - "--pull"

changelog:
  use: github-native
