project_name: trivy-operator-report
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: trivy-operator-report
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-extldflags -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]
    binary: '{{ .ProjectName }}_{{ .Version }}'

archives:
- formats:
    - zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

changelog:
  use: github-native
